/*
 * This file is generated by jOOQ.
 */
package com.scio.cloud.jooq.domain.public_.tables;


import com.scio.cloud.jooq.domain.public_.Indexes;
import com.scio.cloud.jooq.domain.public_.Keys;
import com.scio.cloud.jooq.domain.public_.Public;
import com.scio.cloud.jooq.domain.public_.tables.records.UserInfoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo extends TableImpl<UserInfoRecord> {

    private static final long serialVersionUID = -154620905;

    /**
     * The reference instance of <code>PUBLIC.USER_INFO</code>
     */
    public static final UserInfo USER_INFO = new UserInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserInfoRecord> getRecordType() {
        return UserInfoRecord.class;
    }

    /**
     * The column <code>PUBLIC.USER_INFO.ID</code>.
     */
    public final TableField<UserInfoRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.USER_INFO.PASSWORD</code>.
     */
    public final TableField<UserInfoRecord, String> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>PUBLIC.USER_INFO.REALNAME</code>.
     */
    public final TableField<UserInfoRecord, String> REALNAME = createField("REALNAME", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.USER_INFO.REGISTER_IP</code>.
     */
    public final TableField<UserInfoRecord, String> REGISTER_IP = createField("REGISTER_IP", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.USER_INFO.REGISTER_TIME</code>.
     */
    public final TableField<UserInfoRecord, Timestamp> REGISTER_TIME = createField("REGISTER_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.precision(6), this, "");

    /**
     * The column <code>PUBLIC.USER_INFO.STATUS</code>.
     */
    public final TableField<UserInfoRecord, Integer> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.USER_INFO.USERNAME</code>.
     */
    public final TableField<UserInfoRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * Create a <code>PUBLIC.USER_INFO</code> table reference
     */
    public UserInfo() {
        this(DSL.name("USER_INFO"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.USER_INFO</code> table reference
     */
    public UserInfo(String alias) {
        this(DSL.name(alias), USER_INFO);
    }

    /**
     * Create an aliased <code>PUBLIC.USER_INFO</code> table reference
     */
    public UserInfo(Name alias) {
        this(alias, USER_INFO);
    }

    private UserInfo(Name alias, Table<UserInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserInfo(Name alias, Table<UserInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserInfo(Table<O> child, ForeignKey<O, UserInfoRecord> key) {
        super(child, key, USER_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_B, Indexes.UKF2KSD6H8HSJTD57IPFQ9MYR64_INDEX_B);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserInfoRecord, Long> getIdentity() {
        return Keys.IDENTITY_USER_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<UserInfoRecord>>asList(Keys.CONSTRAINT_B, Keys.UKF2KSD6H8HSJTD57IPFQ9MYR64);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfo as(String alias) {
        return new UserInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfo as(Name alias) {
        return new UserInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInfo rename(String name) {
        return new UserInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInfo rename(Name name) {
        return new UserInfo(name, null);
    }
}
