/*
 * This file is generated by jOOQ.
 */
package com.scio.cloud.jooq.domain.public_.tables.daos;


import com.scio.cloud.jooq.domain.public_.tables.UserInfo;
import com.scio.cloud.jooq.domain.public_.tables.records.UserInfoRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })

@Component
public class UserInfoDao extends DAOImpl<UserInfoRecord, com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo, Long> {

    /**
     * Create a new UserInfoDao without any configuration
     */
    public UserInfoDao() {
        super(UserInfo.USER_INFO, com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo.class);
    }

    /**
     * Create a new UserInfoDao with an attached configuration
     */
    @Autowired
    public UserInfoDao(Configuration configuration) {
        super(UserInfo.USER_INFO, com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchById(Long... values) {
        return fetch(UserInfo.USER_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo fetchOneById(Long value) {
        return fetchOne(UserInfo.USER_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>PASSWORD IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchByPassword(String... values) {
        return fetch(UserInfo.USER_INFO.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>REALNAME IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchByRealname(String... values) {
        return fetch(UserInfo.USER_INFO.REALNAME, values);
    }

    /**
     * Fetch records that have <code>REGISTER_IP IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchByRegisterIp(String... values) {
        return fetch(UserInfo.USER_INFO.REGISTER_IP, values);
    }

    /**
     * Fetch records that have <code>REGISTER_TIME IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchByRegisterTime(Timestamp... values) {
        return fetch(UserInfo.USER_INFO.REGISTER_TIME, values);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchByStatus(Integer... values) {
        return fetch(UserInfo.USER_INFO.STATUS, values);
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo> fetchByUsername(String... values) {
        return fetch(UserInfo.USER_INFO.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>USERNAME = value</code>
     */
    public com.scio.cloud.jooq.domain.public_.tables.pojos.UserInfo fetchOneByUsername(String value) {
        return fetchOne(UserInfo.USER_INFO.USERNAME, value);
    }
}
