/*
 * This file is generated by jOOQ.
 */
package com.scio.cloud.jooq.domain.public_;


import com.scio.cloud.jooq.domain.public_.tables.UserInfo;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
    public static final Index UKF2KSD6H8HSJTD57IPFQ9MYR64_INDEX_B = Indexes0.UKF2KSD6H8HSJTD57IPFQ9MYR64_INDEX_B;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.ID }, true);
        public static Index UKF2KSD6H8HSJTD57IPFQ9MYR64_INDEX_B = Internal.createIndex("UKF2KSD6H8HSJTD57IPFQ9MYR64_INDEX_B", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.USERNAME }, true);
    }
}
