/*
 * This file is generated by jOOQ.
 */
package com.scio.cloud.jooq.domain.public_;


import com.scio.cloud.jooq.domain.public_.tables.UserInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.USER_INFO</code>.
     */
    public static final UserInfo USER_INFO = com.scio.cloud.jooq.domain.public_.tables.UserInfo.USER_INFO;
}
