/*
 * This file is generated by jOOQ.
 */
package com.scio.cloud.jooq.domain.public_.tables.records;


import com.scio.cloud.jooq.domain.public_.tables.UserInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record7<Long, String, String, String, Timestamp, Integer, String> {

    private static final long serialVersionUID = 392128945;

    /**
     * Setter for <code>PUBLIC.USER_INFO.ID</code>.
     */
    public UserInfoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.USER_INFO.PASSWORD</code>.
     */
    public UserInfoRecord setPassword(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.USER_INFO.REALNAME</code>.
     */
    public UserInfoRecord setRealname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.REALNAME</code>.
     */
    public String getRealname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.USER_INFO.REGISTER_IP</code>.
     */
    public UserInfoRecord setRegisterIp(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.REGISTER_IP</code>.
     */
    public String getRegisterIp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.USER_INFO.REGISTER_TIME</code>.
     */
    public UserInfoRecord setRegisterTime(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.REGISTER_TIME</code>.
     */
    public Timestamp getRegisterTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>PUBLIC.USER_INFO.STATUS</code>.
     */
    public UserInfoRecord setStatus(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.STATUS</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>PUBLIC.USER_INFO.USERNAME</code>.
     */
    public UserInfoRecord setUsername(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER_INFO.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Timestamp, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Timestamp, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserInfo.USER_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserInfo.USER_INFO.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserInfo.USER_INFO.REALNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserInfo.USER_INFO.REGISTER_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserInfo.USER_INFO.REGISTER_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UserInfo.USER_INFO.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserInfo.USER_INFO.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRealname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRegisterIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getRegisterTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRealname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRegisterIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getRegisterTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value3(String value) {
        setRealname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value4(String value) {
        setRegisterIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value5(Timestamp value) {
        setRegisterTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value7(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(Long id, String password, String realname, String registerIp, Timestamp registerTime, Integer status, String username) {
        super(UserInfo.USER_INFO);

        set(0, id);
        set(1, password);
        set(2, realname);
        set(3, registerIp);
        set(4, registerTime);
        set(5, status);
        set(6, username);
    }
}
